config/routes.rb
Rails.application.routes.draw do
  require File.expand_path("../../lib/logged_in_constraint", __FILE__)

  get '/' => 'users#home', :constraints => LoggedInConstraint.new(false) # para usuario no logueado
  root :to => 'static_pages#contact', :constraints => LoggedInConstraint.new(true) # para usuario logueado

  match '/unete',  to: 'users#new',            via: 'get'
  match '/condiciones',    to: 'static_pages#cond',    via: 'get'
  match '/politicas',    to: 'static_pages#policy',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contacto', to: 'static_pages#contact', via: 'get'
  match '/salir', to: 'sessions#destroy',     via: 'delete'

  resources :users, :collection=>{:home => :get, :new => :post}
  post 'users/new'

  resources :sessions, only: [:new, :create, :destroy]

  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/policy'
  get 'static_pages/cond'

end

app/models/user.rb
class User < ActiveRecord::Base
  def to_param
    username # use username instead of id
  end

  has_secure_password
  before_create :create_remember_token

	## BEFORE SAVE
	before_save { email.downcase! }
	before_save { username.downcase! }
  before_save { name.capitalize! }
  before_save { surname.split.map(&:capitalize).join(' ') }

	## VALIDATIONS
	validates :username, presence: true, length: { maximum: 15 },
            format: { with: /\A[a-zA-Z0-9]+\Z/ }, 
            uniqueness: { case_sensitive: false } # ni email ni name pueden ser nil
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 50 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :name, presence: true, length: { maximum: 25 },
            format: { with: /\A[a-zA-Z[:alpha:]]+\Z/ } #only letters and tilde
  validates :surname, presence: true, length: { maximum: 50 },
            format: { with: /\A[a-zA-Z[:alpha:]\ ]+\Z/ }
  validates :gender, presence: true, length: { maximum: 1 },
            format: { with: /\A[HM]+\Z/ }
  validates :studies, length: { maximum: 50 },
            format: { with: /\A[a-zA-Z[:alpha:]\ ]+\Z/ }
  validates :birth, presence: true, length: { maximum: 10 },
            format: { with: /\A[0-9\-]+\Z/ }
  validate :old_enough
  # validates :password, length: { minimum: 6 } # validated in password_complexity
  validate :password_complexity



  def password_complexity
    if password.present? and not password.match(/^(?=.*[a-z])(?=.*[A-Z])(?=.*[\d]).{6,}$/)
      errors.add :contraseña, "debe tener al menos 6 carácteres, incluir una mayúscula y un dígito"
    end
  end

  def old_enough
    if 16.years.ago<Date.parse(birth)
      errors.add :debes, "tener más de 16 años"
    end
    rescue ArgumentError
      # catch del error en el que la fecha no sea valida (par apasar test)
  end
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
  end

  def create
  	if params[:session][:login].downcase.match(/\A[a-zA-Z0-9]+\Z/).blank?
  		user = User.find_by(email: params[:session][:login].downcase)
  	else
  		user = User.find_by(username: params[:session][:login].downcase)
  	end
  		  	
	  if user && user.authenticate(params[:session][:pass])
	    sign_in user
	    flash.now[:success] = "Bienvenido "+user.name+"!"
      redirect_to user
	  else
	    flash.now[:error] = 'Email/nombre de usuario o contraseña incorrecta en el inicio de sesión' # Not quite right!
      render :template => "users/home" # para renderizar un metodo de otro controlador"
	  end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	#def home
	#end

  def about
  end

  def contact
  end

  def policy
  end

  def cond
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def home
  end

  def new
  	# para creas usuario
  	@user = User.new

  	# valores que vienen de home
  	@username=params[:username]
  	@email=params[:email]
  	@password=params[:password] 

    if @username.blank? or @email.blank? or @password.blank? or not @password.match(/^(?=.*[a-z])(?=.*[A-Z])(?=.*[\d]).{6,}$/)
      flash.now[:warning] = "No puedes dejar ningun campo en blanco"
      # si la cotnraseña esta prsente tiene que cumplir las condiciones
      if not @password.blank? and not @password.match(/^(?=.*[a-z])(?=.*[A-Z])(?=.*[\d]).{6,}$/)
        flash.now[:warning] = "La contraseña debe tener al menos 6 carácteres, una mayúscula y un dígito"
      end
      render 'home'
    else
      # si el usuario ya esta registrado se emite una viso
      if User.find_by_email(@email)
        flash.now[:warning] = "El email que has introducido ya esta en uso, es posible que ya estes registrado!"
        render 'home'
      elsif User.find_by_username(@username)
        flash.now[:warning] = "El nombre de usuario que has introducido ya esta en uso!"
        render 'home'
      else
        render 'new'
      end
    end 
  end

  def create
    @user = User.new(user_params)
    
    # comprobamos que se guarde bien y que acepte los términos y condiciones
    if @user.save 
      #if params[:acepto]==1
        sign_in @user
        flash.now[:success] = "Bienvenido a PassItEDU "+@user.name+"!"
        redirect_to @user
      #else
      	#@user.errors.add :debes, "aceptar las políticas de privacidad y términos de uso"
      #	render 'new'
      #end
    else
      render 'new'
    end
  end

  def show
  	@user = User.find_by_username(params[:id])
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :username, :birth, :gender, :surname, :studies)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "#YoSoyEDU"
    if page_title.empty?
      base_title
    else
      "#{page_title} - #{base_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end
  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  
  def signed_in?
    !current_user.nil?
  end
  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
  def current_user=(user)
    @current_user = user
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	# Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, size)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-warning alert-dismissible" role="alert" style="margin-top:20px;">
  	<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <%= value %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="dark center-block" id="footer"> <!-- footer !-->
    <ul class="nav navbar-nav"> <!-- menu derecha !-->
        <li><%= link_to("Sobre Nosotros", static_pages_about_path) %></li>
        <li><%= link_to("Contacto", static_pages_contact_path) %></li>
        <li><%= link_to("Políticas de Privacidad", static_pages_policy_path) %></li>
        <li><%= link_to("Condiciones de Uso", static_pages_cond_path) %></li>
    </ul>      
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation"> <!-- requiere padding en el body !-->
  <div class="container">
    <%= link_to("PassItEDU", "/", {:class=>"navbar-brand"}) %><!-- marca !-->
    <form class="navbar-form navbar-left" role="search">
      <div class="input-group">
        <input type="text" class="form-control">
        <span class="input-group-btn">
          <button class="btn btn-default" type="button">Buscar</button>
        </span>
      </div><!-- /input-group -->
    </form>
    <ul class="nav navbar-nav navbar-right"> <!-- menu derecha !-->
    
      <% if signed_in? %>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <%= current_user.name %> <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Timeline", '#' %></li>
            <li><%= link_to "Mi Perfil", current_user %></li>
            <li><%= link_to "Opciones", '#' %></li>
            <li class="divider"></li>
            <li><%= link_to "Salir", salir_path, method: "delete" %></li>
          </ul>
        </li>
      <% else %>
        <div class="navbar-form navbar-right">
          <%= form_for(:session, url: sessions_path) do |f| %>
            <div class="input-group" id="formLogin">
              <%= f.text_field :login, placeholder: 'Nombre de usuario/email', class: 'form-control', style: 'width:210px;margin-right:20px;' %>
              <%= f.password_field :pass, placeholder: 'Contraseña', class: 'form-control', style: 'width:210px;margin-right:20px;' %>
              <%= f.button 'Iniciar Sesión', class: 'btn btn-large btn-info' %>
            </div>
          <% end %>
        </div>
      <% end %>
   
    </ul>
  </div>
</nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Roboto:400,400italic,700,700italic'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<%= render 'layouts/flash' %>
		<%= yield %>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div class="alert alert-warning alert-dismissible" role="alert" style="margin-top:20px;">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      El formulario contiene <%= pluralize(@user.errors.count, "error") %>.
		    <ul>
		    <% @user.errors.full_messages.each do |msg| %>
		      <li><%= msg %></li>
		    <% end %>
		    </ul>
    </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'Sobre Nosotros') %>

<div class="row">
<div class="panel panel-default"> 
  <div class="panel-body" style="padding:30px;">
  	<div class="page-header" style="margin-top:-10px">
  		<h1>Sobre Nosotros</h1>
		</div>

		<center>
		<div class="embed-responsive embed-responsive-16by9" style="margin:20px;">
			<iframe class="embed-responsive-item" src="http://www.youtube.com/embed/OwVWlsbjMd0?feature=player_detailpage" frameborder="0"  allowfullscreen></iframe>
		</div>
		<p> Buenas, somos <b>Adrián</b> y <b>Fran</b> y nosotros formamos <b>Pass-It</b>. Somos <b>dos estudiantes</b> de Ingeniería de Software en la Universidad de Málaga y por supuesto no somos matemáticos ni mucho menos. Nuestra <b>idea</b> es crear una comunidad sencilla en la que todos nos podamos <b>ayudar</b> a afrontar las dificultades que nos encontramos en nuestros estudios día a día. No solo intentamos ayudar con nuestros vídeos (que distan mucho de ser algo profesionales) sino que <b>intentamos</b> por todos los medios <b>crear una comunidad</b> donde todos nos ayudemos a todos. Porque nadie es experto en lo que sabe, empezando por <b>nosotros</b>, pero estamos seguro de que todos siempre podemos aportar un granito de arena. Espero que sea una buena experiencia, que os ayude, y que consigamos llegar lejos <b>todos juntos</b>. 
		<br></br>
		Un cordial saludo de PassItEDU, de parte de Fran y Adrián.
		</center>
    
	</div>
</div>
</div>

app/views/static_pages/cond.html.erb
<% provide(:title, 'Términos de Uso') %>

<div class="row">
<div class="panel panel-default"> 
  <div class="panel-body" style="padding:30px;">
  	<div class="page-header" style="margin-top:-10px">
  		<h1>Términos de Uso</h1>
		</div>
    
      Gracias por visitar www.passitedu.es (en adelante la Web). Esta web es propiedad de Adrián González Leiva y Francisco Navarro Aguilar (en adelante PassItEDU) con localización en Málaga. Recordarle a usted (en adelante el Usuario) que nos reservamos el derecho de modificar estas condiciones de uso en cualquier momento, con la respectiva notificación a los Usuarios sobre las novedades.
      <br></br>
      Al ser un proyecto, estaremos constantemente añadiendo funcionalidades y cambios a la web, por lo que estas Condiciones de Uso cambiarán bastante de aquí al lanzamiento de la plataforma, por lo que recomendamos al Usuario que consulte este texto con cierta asiduidad para conocer todas las novedades y cambios que le conciernen.

    <h3>¿Qué es PassItEDU?</h3>

      PassItEDU es un portal de enseñanza con un canal de Youtube con multitud de vídeos sobre matemáticas en distintos niveles de enseñanza (ESO, Bachiller, Universidad, etc.) entre otras asignaturas. principalmente enfocado a Ingenierías a nivel Universitario, pero con mucho contenido básico de Matemáticas. Ofrece también un foro de dudas donde poder preguntar, responder o compartir información entre alumnos.

    <h3>Entonces, ¿cuál es el cambio?</h3>

      Ahora también la Web ofrecerá un portal de enseñanza online, donde a forma de red social, cada usuario podrá crear su perfil para subir sus apuntes, ya sea en formato de texto, PDF, o digitalizados, y así poder compartirlos con el resto de usuarios de la comunidad. Cada usuario a parte de tener el rol de profesor, también podrán actuar como alumno, leyendo los apuntes de otros usuarios y siguiendo a determinados profesores para poder enterarse de todos los apuntes que suben al portal. Todos los apuntes, sea cual sea el curso, o los estudios que estas cursando tendrán lugar en la Web.

    <h3>Registro en la plataforma</h3>

      Al estar todavía en una etapa muy pronto del desarrollo, el único formulario que el Usuario tiene a su disposición es el de registro en la plataforma. Este formulario simplementa pedirá al Usuario nombre y apellidos, el email (para poder notificar de todas las novedades) y datos estadísticos como la fecha de nacimiento y los estudios que esta cursando para conocer mejor al Usuario y poder ofrecer una experiencia más personalizada.
      <br></br>
      Es importante que el Usuario lea las Políticas de Privacidad además de este texto, porque para darse de alta en nuestra plataforma, tendrá que estar totalmente conforme con estos textos.
      <br></br>
      Otro detalle importante para el Usuario y que debe conocer, es que la edad mínima de acceso a esta plataforma (aunque todavía este en beta) es de 16 años. En el caso de encontrarte por debajo de esa edad, lo sentimos pero todavía tendrás que esperar un par de años para poder acceder. En el caso de que seas mayor de 16 años, pero seas todavía menor de edad, tendrás que informar y consultar con tus padres o tutores legales el acceso a la plataforma, y que estos te den pleno consentimiento para registrarte, en otro caso, PassItEDU estará en pleno derecho de borrar tu usuario de nuestra base de datos.

    <h3>Uso de cookies</h3>

      Todavía al estar en fase beta, no hacemos uso de las cookies. Si quieres más información acerca de ellas pásate por la Política de Privacidad o ve al apartado de contacto.

    <h3>Contacto</h3>

      Hasta que la plataforma no esté mas avanzada, no podremos actualizar ni definir más estas Condiciones de Uso, de mientras, si tenéis alguna duda, queja o sugerencia por favor, escríbenos a passitedu[at]gmail.com 
	</div>
</div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contacto') %>

<div class="row">
<div class="panel panel-default"> 
  <div class="panel-body" style="padding:30px;">
  	<div class="page-header" style="margin-top:-10px">
  		<h1 >Contacto</h1>
  		<div class="col-md-4" style="height:370px;margin:15px auto 25px auto;border-right:solid #D8D8D8;">
  			<h2 style="color:red;margin-bottom:30px;">Youtube</h2>
  			<script src="https://apis.google.com/js/platform.js"></script>
				<div class="g-ytsubscribe" data-channel="Passitedu" data-layout="full" data-count="undefined">
				</div>
				<br><br>
				<p>Este es nuestro canal, puedes preguntarnos dudas de alg&uacute;n video directamente en la zona de comentarios, tambi&eacute;n puedes mandarnos alguna petici&oacute;n a trav&eacute;s de un mensaje directo al canal y la contestaremos rapidamente.</p>
  		</div>
  		<div class="col-md-4" height="250" style="height:370px;margin:15px auto 25px auto;border-right: solid #D8D8D8">
  			<h2 style="margin-bottom:10px;color:#33ccff;">Twitter</h2>
	  		<a class="twitter-timeline" width="300" height="250" href="https://twitter.com/PassItEDU" data-widget-id="489422785647607808">Tweets por @PassItEDU</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
				</script>
				<p>Puedes contactarnos por Twitter si quieres compartir algo con el resto de seguidores.</p>
  		</div>
  		<div class="col-md-4" style="height:370px;margin:15px auto 25px auto;">
  			<h2 style="color:#3B5998;">Facebook</h2>
  			<iframe src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2FPassitedu&amp;width=300&amp;height=290&amp;colorscheme=light&amp;show_faces=true&amp;header=true&amp;stream=false&amp;show_border=true" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:300px; height:290px;" allowTransparency="true">
  			</iframe>
  		</div>
  		<p>Por ultimo, si necesitas decirnos algo de una manera mas personal, o bien tienes alguna duda, queja, o sugerencia, puedes contactar con nosotros por estas dos vias:<br>
        contacto[at]passitedu.es o dudas[at]passitedu.es<br><br><br></p>
		</div>

	</div>
</div>
</div>

app/views/users/home.html.erb
<% provide(:title, 'Bienvenidos') %>

<div class="row" style="padding:20px;">
	<div class="col-md-6 dark" id="home-left"> <!-- left !-->
		<h2>Bienvenidos</h2>
	  <div class="media">
	    <%= link_to(image_tag("bomb.png", :height => "64", :width => "64"), "#", {:class=>"pull-left"}) %>
	    </a>
	    <div class="media-body">
	      <h3 class="media-heading">Aprende</h3>
	      Podrás buscar apuntes de otros estudiantes.
	    </div>
	  </div>
	  <div class="media">
	      <%= link_to(image_tag("mascotacolor.png", :style => "margin:0 10px 0 20px;", :height => "64", :width => "35"), "#", {:class=>"pull-left"}) %>
	    <div class="media-body">
	      <h3 class="media-heading">Enseña</h3>
	      Registrate y sube tus propios apuntes.
	    </div>
	  </div>
	  <div class="media">
	    <%= link_to(image_tag("red.png", :height => "64", :width => "64"), "#", {:class=>"pull-left"}) %>
	    <div class="media-body">
	      <h3 class="media-heading">Comparte</h3>
	      En las redes sociales.
	    </div>
	  </div>
	</div>

	<div class="col-md-6 dark" id="home-right"> <!-- right !-->
			<h1>Únete</h1>
			<%= form_tag '/users/new' do %>
			
      <div class="form-group"><%= text_field_tag 'username', nil, placeholder: "Elige un nombre de usuario", class: "form-control" %></div>

      <div class="form-group"><%= email_field_tag 'email', nil, placeholder: "pepito@ejemplo.com", class: "form-control" %>
				<p class="help-block" style="color:#dfdfdf;">Recuerda: tienes que usar un email válido.</p>
      </div>

      <div class="form-group"><%= password_field_tag 'password', nil, placeholder: "Elige tu contraseña", class: "form-control" %>
      	<p class="help-block" style="color:#dfdfdf;">Mínimo 6 caractéres, al menos una mayúscula y un número.</p>
      </div>

      <%= submit_tag "Enviar", class: "btn btn-large btn-primary" %>
      
    <% end %>
	</div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Únete') %>
  <h1 class="dark">Únete</h1>
  <div class="col-md-6 dark" id="form">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

      <div class="form-group">
      <%= f.label 'Sobre ti' %>
      <%= f.text_field :name, placeholder: 'Nombre', class: 'form-control', style: 'width:30%' %>
      </div>
      <div class="form-group">
      <%= f.text_field :surname, placeholder: 'Apellidos', class: 'form-control', style: 'width:50%' %>
      </div>
      <div class="form-group">
      <%= f.text_field :studies, placeholder: 'Dinos qué estudias o has estudiado (Opcional)', class: 'form-control', style: 'width:60%' %>
      </div>
      <div class="form-group">
      <%= f.radio_button :gender, 'H' %>
      <%= f.label 'Hombre' %>
      <%= f.radio_button :gender, 'M' %>
      <%= f.label 'Mujer' %>
      </div>

      <div class="form-group">
      <%= f.date_field :birth, class: 'form-control', style: 'width:30%' %>
      <p class="help-block" style="color:#dfdfdf;">Recuerda: tienes que tener mas de 16 años.</p>
      </div>
      
      <div class="form-group">
      <%= f.label 'Para la web' %>
      <%= f.text_field :username, placeholder: 'Elige un nombre de usuario', value: @username, class: 'form-control', style: 'width:50%' %>
      </div>
      <div class="form-group">
      <%= f.email_field :email, placeholder: 'pepito@example.com', value: @email, class: 'form-control', style: 'width:50%' %>
      </div>
      <div class="form-group">
      <%= f.password_field :password, placeholder: 'Elige tu contraseña', value: @password, class: 'form-control', style: 'width:50%' %>
      </div>
      <div class="form-group">
      <%= f.password_field :password_confirmation, placeholder: 'Confirma tu contraseña', class: 'form-control', style: 'width:50%' %>
      </div>

      <div class="form-group">
        <%= check_box_tag :acepto %>
        He leído y acepto las <%= link_to 'Política de Privacidad', static_pages_policy_path %> y <%= link_to 'Términos de Uso', static_pages_cond_path %>
      </div>
    
      <%= f.submit "Enviar", class: "btn btn-large btn-info" %>
    <% end %>
  </div>
  
  <div class="col-md-6" id="intro">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="panel-title">¿Cómo funciona PassItEDU?</h2>
      </div>
      <div class="panel-body" style="width:550px;">
        <%= image_tag 'mascotacolor.png', height: '100' , width: '55', align: 'left', style: 'margin-right:10px;' %>

        <p>
          Bienvenido! yo soy Edu y te voy a contar como funciona la web.
          <h4>¿Que puedo hacer?</h4>
          Una vez que te registres en la web, podrás <b>subir tus apuntes</b> a la web de la forma que tu prefieres, ya sea en formato de <b>texto</b>, un <b>PDF</b>, o una <b>imagen escaneada</b>.
          <h4>¿Por qué 'era social'?</h4>
          Claro! Ahora en PassitEDU podrás <b>seguir</b> a otros usuarios para enterarte cuando suben apuntes nuevos, incluso <b>puntuarlos</b> y mandar comentarios o mensajes privados para ponerte en contacto con ellos.
          <br></br>
          Quiero que <b>compartir tus apuntes</b> sea ahora más fácil que nunca. Pero siempre podrás elegir si un <b>invitado</b> puede ver tus apuntes, o tiene que unirse a nosotros!
          <h4>¿Pero a qué precio?</h4>
          <b>Totalmente gratis</b>! Veras publicidad que nos ayuda a mantener el sitio activo, pero trataré que sea lo menos molesta para que tu experiencia sea lo mas comoda posible.
        </p>
        <hr style="width:100px;">
        <%= image_tag 'gomalapiz.png', height: '100' , width: '100', style: 'display: block;margin:-10px auto 0 auto;' %>
      </div>
    </div>
  </div>